allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - zod@4.5.4
  - tsx@4.23.13
  - pg-boss@12.30.0
overrides:
  deepmerge-ts: 8.0.0
