import Link from "next/link";
import { LoginDialog } from "../../modules/identity-access/client.ts";
import { LeadRequestDialog } from "./LeadRequestDialog.tsx";
import { SiteFooter } from "./SiteFooter.tsx";
import styles from "./ImpulseLanding.module.css";

function PublicHeader({ loginRequested, oauthLoginRequested }: { loginRequested: boolean; oauthLoginRequested: boolean }) {
  return <header className="mx-auto flex w-full max-w-[1360px] items-center justify-between px-5 py-5 sm:px-6 lg:py-7"><Link href="/" className="inline-flex min-h-11 items-center gap-3 text-[var(--ch-white)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ch-accent)] focus-visible:ring-offset-4 focus-visible:ring-offset-[var(--ch-bg-deepest)]" aria-label="AMS IMPULSE — главная"><span className="grid size-10 place-items-center border border-[var(--ch-border-hover)] bg-[var(--ch-surface-subtle)] text-[11px] font-extrabold tracking-[-0.04em]">AMS</span><span className="text-sm font-extrabold tracking-[0.16em]">IMPULSE</span></Link><LoginDialog initialOpen={loginRequested} oauthLoginRequested={oauthLoginRequested} /></header>;
}

function HeroCopy() {
  return <div className="relative z-10 max-w-3xl"><p className="mb-6 text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--ch-accent)]">Продвижение сайтов в Яндексе</p><h1 className="max-w-[850px] text-[clamp(44px,6.2vw,84px)] font-extrabold leading-[0.98] tracking-[-0.045em] text-[var(--ch-white)]">Быстрое продвижение сайтов в SEO</h1><p className="mt-7 max-w-2xl text-[clamp(17px,1.45vw,21px)] leading-[1.62] text-[var(--ch-soft-white)]">Быстрое и безопасное продвижение сайтов в топ-1 выдачи Яндекс с помощью уникальных технологий.</p><div className="mt-9 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><LeadRequestDialog /><p className="max-w-[285px] text-xs leading-5 text-[var(--ch-muted-ondark)]">Регистрируйся в личном кабинете и получай бесплатный тест-драйв на 5 дней.</p></div><div className="mt-14 flex flex-wrap gap-x-7 gap-y-3 border-t border-[var(--ch-border-subtle)] pt-5 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--ch-copy-ondark)]"><span>Поведенческие факторы</span><span>Яндекс</span><span>Контроль динамики</span></div></div>;
}

function HeroVisual() {
  return <div className="relative min-h-[420px] lg:min-h-[620px]" aria-hidden><div className={`${styles.visual} absolute inset-0 overflow-hidden border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-deeper)]/55`}><div className="absolute inset-0 bg-[image:var(--ch-hero-gradient)]" /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 560 680" fill="none"><path d="M-20 586C115 498 178 529 268 403C351 288 406 184 596 106" stroke="var(--ch-data-line)" strokeWidth="2" /><path d="M-15 620C138 535 201 552 302 427C389 319 428 215 602 148" stroke="var(--ch-data-line-faint)" strokeWidth="1" /><path d="M30 552L138 478L219 503L316 353L419 302L532 162" stroke="var(--ch-data-line-soft)" strokeWidth="1" /><circle cx="138" cy="478" r="5" fill="var(--ch-accent)" /><circle cx="219" cy="503" r="4" fill="var(--ch-soft-white)" /><circle cx="316" cy="353" r="6" fill="var(--ch-accent)" /><circle cx="419" cy="302" r="4" fill="var(--ch-soft-white)" /><circle cx="532" cy="162" r="7" fill="var(--ch-accent)" /></svg><div className="absolute left-6 top-6 border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-deepest)]/75 px-4 py-3 backdrop-blur-sm sm:left-8 sm:top-8"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--ch-subtle-ondark)]">Сигнал роста</p><p className="mt-1 text-2xl font-bold tracking-[-0.03em] text-[var(--ch-white)]">+ импульс</p></div><div className="absolute bottom-7 right-6 w-[min(280px,calc(100%_-_48px))] border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-dark)]/88 p-5 backdrop-blur-md sm:bottom-9 sm:right-8"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[var(--ch-subtle-ondark)]">Динамика</p><p className="mt-2 text-lg font-bold text-[var(--ch-white)]">Позиции в Яндексе</p></div><span className="size-2 bg-[var(--ch-accent)] shadow-[var(--ch-signal-ring)]" /></div><div className="mt-5 grid grid-cols-5 items-end gap-2">{[26, 36, 48, 68, 92].map((height, index) => <span key={height} className="block bg-[var(--ch-accent)]/75" style={{ height, opacity: 0.45 + index * 0.12 }} />)}</div></div></div></div>;
}

export function ImpulseLanding({ loginRequested, oauthLoginRequested = false }: { loginRequested: boolean; oauthLoginRequested?: boolean }) {
  return <main className="theme-public impulse-landing min-h-screen overflow-hidden bg-[var(--ch-bg-deepest)] text-[var(--ch-white)]"><section className="relative isolate min-h-screen"><div className={`${styles.grid} absolute inset-0 -z-20`} aria-hidden /><div className={`${styles.atmosphere} absolute inset-0 -z-10`} aria-hidden /><PublicHeader loginRequested={loginRequested} oauthLoginRequested={oauthLoginRequested} /><div className="mx-auto grid w-full max-w-[1360px] gap-12 px-5 pb-12 pt-14 sm:px-6 sm:pt-20 lg:min-h-[calc(100vh-96px)] lg:grid-cols-[minmax(0,7fr)_minmax(360px,5fr)] lg:items-center lg:gap-16 lg:pb-20 lg:pt-10"><HeroCopy /><HeroVisual /></div></section><SiteFooter /></main>;
}
